apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiaeventdistribution
  namespace: personoversikt
  labels:
    team: personoversikt
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: modiaeventdistribution/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: modiaeventdistribution/internal/isReady
    initialDelay: 20
    timeout: 1
  replicas:
    min: 4
    max: 6
    cpuThresholdPercentage: 60
  prometheus:
    enabled: true
    path: modiaeventdistribution/internal/metrics
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 600m
      memory: 512Mi
  ingresses:
    - https://modiaeventdistribution.nais.adeo.no/modiaeventdistribution
    - https://veilederflatehendelser.adeo.no/modiaeventdistribution
    - https://veilederflatehendelser.intern.nav.no/modiaeventdistribution
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvmodiaeventdistribution
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /apikey/appdynamics/prod
        mountPath: /var/run/secrets/nais.io/vault
  envFrom:
    - secret: modiacontextholder-redis-passord
  env:
    - name: APP_NAME
      value: "modiaeventdistribution"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: APP_ENVIRONMENT
      value: "p"
    - name: REDIS_HOST
      value: "modiacontextholder-redis.personoversikt.svc.nais.local"
